### ISSUE TITLE
linked entities not highlighted in text viewer

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#52]
https://github.com/bioentity/papers/issues/1296
https://bioentity.link/#/publication/10.1534%2Fg3.119.400897
Also unlinking entities does not remove highlighting in the text. Please see the issue reported by @suzialeksander in the paper issue tracker.

**Comment by nickstiffler** [comment]
There appear to be many issues with the manual linking tool. When creating links, the wrong url is put in the xml and then doesn't have the correct styling. Deleting links deletes from the database, but not the xml. When linking a term that has an entry in the lexicon database, a new entry is created rather than referencing the existing lexica. It should lookup the external MOD ID and use that lexicon if it exists.

**Comment by kyook** [comment]
Those issues seem pretty important.  Particularly the one about inserting wrong urls and not deleting from the xml. Are you able to address those?

**Comment by kyook** [comment]
@nickstiffler Can you roll back the changes to restore proper xml linking/deleting functions?

**Comment by nickstiffler** [comment]
I haven't made any changes. This is the way it has always been. It would be better to fix these issues.

**Comment by kyook** [comment]
ok,  there is a yeast paper I'd like to link and send, but I'd rather wait until the fix is in, it is too frustrating for the curator to deal with the bugs. If you would let me know when they are fixed, I'll pass the paper along then.  thanks!

**Comment by nickstiffler** [comment]
Those fixes are in place now. I think this will resolve many of the frustrations Suzi was having. 

It would be good to discuss improvements that can be made to the link popup. For example, the "reason for adding" drop down doesn't have the most common reason people seem to be using this: "Lexicon exists, but was not linked".

The other issue you were having where the link is not the correct color after linking still persists. This is because the link object is created before the URL is assigned, and the browser tries to render it, but there is no link yet to know what species color to add. Reloading the page works to fix this, so it shouldn't be a problem for now as long as you do the linking before sending it others.

**Comment by suzialeksander** [comment]
@nickstiffler will you be at Alliance All Hands? That may be a great time to set up a breakout there to discuss.  I'm missing the pre-meeting but will be there both main days.

**Comment by nickstiffler** [comment]
Hi @suzialeksander 

Yes, I will be there the same time as you and that sounds like a great plan. I haven't scrutinized over the agenda yet, but maybe you or @kyook will have a suggestion about when to plan a meeting time.

**Comment by kyook** [comment]
Good idea @suzialeksander. I'll be there for the main days as well. It would be great to get your feedback as well as ideas on how to make things easier.  I will look over the schedule, but either of you see a spot, let me know.

**Comment by kyook** [comment]
this article shows some linking highlighting discrepancies. I have only run the linking script with SGD_gap https://bioentity.link/#/publication/10.1534/g3.119.400606
I have not tried to add or delete links however the links do show up in different colors. Shouldn't they all have the same styling?

**Comment by suzialeksander** [comment]
This is still an issue in 10.1534/g3.119.400606 #1303, and worse, the link menu on the right is very buggy.  Comments on paper's GH.
